"""Public Tile harness facade."""

from tile.exceptions import TurnFailedError
from tile.providers import Provider
from tile.result import (
    AbortReason,
    Aborted,
    AgentFailure,
    Completed,
    ExecutionFailure,
    ExecutionFailureOrigin,
    Failed,
    FailureCause,
    Faulted,
    RunOutcome,
    RunResult,
)
from tile.runtime import AgentHarness, RunHandle
from tile.sessions import Session, SessionRepository
from tile.store import (
    ActiveRunError,
    HistoryItem,
    InvalidHistoryError,
    RunAlreadyExistsError,
    RunNotFoundError,
    RunRecord,
    RunStatus,
    SessionAlreadyExistsError,
    SessionNotFoundError,
    SessionRecord,
    SQLiteStore,
    SQLiteStoreSchemaError,
    StaleRunError,
    Store,
    StoreError,
    StoreOperation,
    StorePersistenceError,
)
from tile.tool_executor import ToolExecutor

__all__ = [
    "AbortReason",
    "Aborted",
    "ActiveRunError",
    "AgentFailure",
    "AgentHarness",
    "Completed",
    "ExecutionFailure",
    "ExecutionFailureOrigin",
    "Failed",
    "FailureCause",
    "Faulted",
    "HistoryItem",
    "InvalidHistoryError",
    "Provider",
    "RunAlreadyExistsError",
    "RunHandle",
    "RunNotFoundError",
    "RunOutcome",
    "RunRecord",
    "RunResult",
    "RunStatus",
    "SQLiteStore",
    "SQLiteStoreSchemaError",
    "Session",
    "SessionAlreadyExistsError",
    "SessionNotFoundError",
    "SessionRecord",
    "SessionRepository",
    "StaleRunError",
    "Store",
    "StoreError",
    "StoreOperation",
    "StorePersistenceError",
    "ToolExecutor",
    "TurnFailedError",
]
